# Generated by Django 4.2 on 2023-05-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deaf_undead", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("Deaf", "Deaf"), ("Undeaf", "Undeaf")],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="FriendShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("declined", "declined"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_sender",
                        to="deaf_undead.newuser",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendship_receiver",
                        to="deaf_undead.newuser",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
