# Generated by Django 4.2 on 2023-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deaf_undead", "0004_allcourses_course_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="newuser",
            name="favorite_courses",
            field=models.ManyToManyField(to="deaf_undead.allcourses"),
        ),
    ]
