# Generated by Django 4.2 on 2023-05-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deaf_undead", "0005_newuser_favorite_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavouritCourses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deaf_undead.coursescategories",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="deaf_undead.newuser",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Favourite Courses",
            },
        ),
    ]
